"""
Django settings for Registro_Articulo project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os # <--- NECESARIO para manejar rutas y .env
from pathlib import Path
import environ # <--- NECESARIO para manejar variables de entorno

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------
# CONFIGURACIÓN DE DJANGO-ENVIRON
# ----------------------------------------------------
# Inicializar django-environ
env = environ.Env(
    # Define el valor por defecto si DATABASE_URL no se encuentra
    DATABASE_URL=(str, 'sqlite:///db.sqlite3') 
)

# Esto busca el archivo .env en el directorio raíz de tu proyecto (donde está manage.py)
environ.Env.read_env(os.path.join(BASE_DIR, '.env')) 
# ----------------------------------------------------


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# AHORA LEE LA CLAVE SECRETA DEL ARCHIVO .ENV
SECRET_KEY = env('SECRET_KEY') 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Mantenemos DEBUG en True para desarrollo

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'solicitudes_app',
    'rest_framework', # Asumo que lo usas
    'rest_framework.authtoken', # Asumo que lo usas
    'corsheaders', # Asumo que lo usas
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Middleware de CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Registro_Articulo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Registro_Articulo.wsgi.application'


# ----------------------------------------------------
# CONFIGURACIÓN DE BASE DE DATOS (Supabase/PostgreSQL)
# ----------------------------------------------------
# Reemplaza la configuración predeterminada de DATABASES:
DATABASES = {
    # Esto lee la variable DATABASE_URL del archivo .env
    'default': env.db() 
}

if 'postgresql' in DATABASES['default']['ENGINE']:
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        # Puedes añadir SessionAuthentication para la interfaz web de Django
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}

# Configuración de CORS
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",  # Tu frontend React local
    "http://localhost:3000",
    # Añadir dominios de producción aquí si es necesario
]

# Permitir credenciales (cookies, etc.) para solicitudes de origen cruzado
CORS_ALLOW_CREDENTIALS = True

# settings.py

# Use la URL de Render cuando la sepa, o use '*' temporalmente
ALLOWED_HOSTS = ['*', 'su-dominio-de-render.onrender.com'] 

# Importante: Desactive el modo DEBUG en producción
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'